from PIL import Image, ImageDraw

def create_graphic(headline):

    width = 1080
    height = 1080

    image = Image.new("RGB", (width, height), (12, 18, 35))

    draw = ImageDraw.Draw(image)

    # Header
    draw.rectangle(
        [(0, 0), (1080, 120)],
        fill=(20, 120, 255)
    )

    draw.text(
        (40, 40),
        "FOOTBALL AI",
        fill=(255, 255, 255)
    )

    # Breaking banner
    draw.rectangle(
        [(40, 180), (500, 260)],
        fill=(220, 40, 40)
    )

    draw.text(
        (60, 205),
        "BREAKING NEWS",
        fill=(255, 255, 255)
    )

    # Main headline
    headline = headline[:100]

    draw.text(
        (60, 350),
        headline,
        fill=(255, 255, 255)
    )

    # Footer
    draw.line(
        [(60, 900), (1020, 900)],
        fill=(255, 255, 255),
        width=3
    )

    draw.text(
        (60, 940),
        "Generated by Football AI",
        fill=(180, 180, 180)
    )

    filename = "static/latest_graphic.png"

    image.save(filename)

    return filename
