from PIL import Image, ImageDraw

def create_graphic(headline):

    width = 1080
    height = 1080

    image = Image.new("RGB", (width, height), (8, 12, 30))

    draw = ImageDraw.Draw(image)

    # Top banner
    draw.rectangle(
        [(0, 0), (1080, 120)],
        fill=(0, 102, 255)
    )

    draw.text(
        (40, 40),
        "FOOTBALL AI",
        fill=(255, 255, 255)
    )

    # Breaking news banner
    draw.rectangle(
        [(40, 170), (450, 250)],
        fill=(220, 40, 40)
    )

    draw.text(
        (60, 195),
        "BREAKING NEWS",
        fill=(255, 255, 255)
    )

    # Format headline into multiple lines
    words = headline.upper().split()

    lines = []
    current = ""

    for word in words:

        if len(current + " " + word) < 18:
            current += " " + word
        else:
            lines.append(current.strip())
            current = word

    lines.append(current)

    y = 340

    for line in lines[:4]:

        draw.text(
            (60, y),
            line,
            fill=(255, 255, 255)
        )

        y += 90

    # Subheading
    draw.text(
        (60, 760),
        "LATEST FOOTBALL UPDATE",
        fill=(180, 180, 180)
    )

    # Footer line
    draw.line(
        [(60, 900), (1020, 900)],
        fill=(255, 255, 255),
        width=3
    )

    draw.text(
        (60, 940),
        "Generated by Football AI",
        fill=(180, 180, 180)
    )

    filename = "static/latest_graphic.png"

    image.save(filename)

    return filename
