from PIL import Image, ImageDraw, ImageFont

def create_graphic(headline):

    width = 1080
    height = 1080

    image = Image.new("RGB", (width, height), (10, 15, 35))

    draw = ImageDraw.Draw(image)

    # Fonts
    title_font = ImageFont.truetype(
        "fonts/Anton-Regular.ttf",
        120
    )

    banner_font = ImageFont.truetype(
        "fonts/Anton-Regular.ttf",
        65
    )

    footer_font = ImageFont.truetype(
        "fonts/Anton-Regular.ttf",
        40
    )

    # Header
    draw.rectangle(
        [(0, 0), (1080, 120)],
        fill=(0, 102, 255)
    )

    draw.text(
        (40, 20),
        "FOOTBALL AI",
        font=banner_font,
        fill=(255, 255, 255)
    )

    # Breaking banner
    draw.rectangle(
        [(40, 170), (520, 260)],
        fill=(220, 30, 30)
    )

    draw.text(
        (70, 185),
        "BREAKING NEWS",
        font=banner_font,
        fill=(255, 255, 255)
    )

    # Headline formatting
    words = headline.upper().split()

    lines = []
    current = ""

    for word in words:

        if len(current + " " + word) <= 15:
            current += " " + word
        else:
            lines.append(current.strip())
            current = word

    lines.append(current)

    y = 340

    for line in lines[:4]:

        draw.text(
            (60, y),
            line,
            font=title_font,
            fill=(255, 255, 255)
        )

        y += 130

    # Decorative line
    draw.line(
        [(60, 880), (1020, 880)],
        fill=(255, 255, 255),
        width=4
    )

    # Footer
    draw.text(
        (60, 930),
        "GENERATED BY FOOTBALL AI",
        font=footer_font,
        fill=(180, 180, 180)
    )

    filename = "static/latest_graphic.png"

    image.save(filename)

    return filename
